config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im-oaipmh-client:
      branch: main
      repo: https://github.com/grycap/im-oaipmh-client.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im-oaipmh-client git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-olive-quokka.sh
        container: qc.acc_trippy-eggplant-dunker
  QC.Doc:
    repos:
      github.com/grycap/im-oaipmh-client find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-flax-husky.sh
        container: qc.doc_ready-pink-cichlid
      github.com/grycap/im-oaipmh-client git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-khaki-labradoodle.sh
        container: qc.doc_lumpy-celadon-coral
      github.com/grycap/im-oaipmh-client markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-fuchsia-gecko.sh
        container: qc.doc_scanty-tomato-whippet
  QC.Lic:
    repos:
      github.com/grycap/im-oaipmh-client licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-chocolate-eagle.sh
        container: qc.lic_homely-crimson-wombat
  QC.Met:
    repos:
      github.com/grycap/im-oaipmh-client validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.homely-scarlet-grouse.sh
        container: qc.met_homely-cerise-wolfhound
  QC.Sec:
    repos:
      github.com/grycap/im-oaipmh-client bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-orange-barracuda.sh
        container: qc.sec_geeky-teal-butterfly
  QC.Sty:
    repos:
      github.com/grycap/im-oaipmh-client flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-amber-beaver.sh
        container: qc.sty_snippy-plum-mau
      github.com/grycap/im-oaipmh-client jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-maroon-goose.sh
        container: qc.sty_flimsy-emerald-turkey
  QC.Uni:
    repos:
      github.com/grycap/im-oaipmh-client pytest:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-peach-nightingale.sh
        container: qc.uni_pretty-eggplant-bear
  QC.Ver:
    repos:
      github.com/grycap/im-oaipmh-client get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-persimmon-gopher.sh
        container: qc.ver_crappy-corn-ray
timeout: 5400
