config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im-oaipmh-client:
      branch: main
      repo: https://github.com/grycap/im-oaipmh-client.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im-oaipmh-client git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-salmon-burmese.sh
        container: qc.acc_cheeky-harlequin-ragdoll
  QC.Doc:
    repos:
      github.com/grycap/im-oaipmh-client find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-chartreuse-ferret.sh
        container: qc.doc_randy-burgundy-avocet
      github.com/grycap/im-oaipmh-client git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-wheat-manatee.sh
        container: qc.doc_wimpy-black-mammoth
      github.com/grycap/im-oaipmh-client markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-olive-kangaroo.sh
        container: qc.doc_wiggy-wheat-moth
  QC.Lic:
    repos:
      github.com/grycap/im-oaipmh-client licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-cinnabar-ferret.sh
        container: qc.lic_pretty-scarlet-wolf
  QC.Met:
    repos:
      github.com/grycap/im-oaipmh-client validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-indigo-molly.sh
        container: qc.met_chewy-carmine-falcon
  QC.Sec:
    repos:
      github.com/grycap/im-oaipmh-client bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-plum-yak.sh
        container: qc.sec_muggy-green-wasp
  QC.Sty:
    repos:
      github.com/grycap/im-oaipmh-client flake8:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-wisteria-paradise.sh
        container: qc.sty_flabby-ivory-manatee
      github.com/grycap/im-oaipmh-client jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-aqua-ibis.sh
        container: qc.sty_pasty-vermilion-binturong
  QC.Uni:
    repos:
      github.com/grycap/im-oaipmh-client pytest:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-sangria-tang.sh
        container: qc.uni_skanky-beige-cockroach
  QC.Ver:
    repos:
      github.com/grycap/im-oaipmh-client get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-orange-sloth.sh
        container: qc.ver_silly-dandelion-leopard
timeout: 5400
